tages:
  - build
  - deploy-production

variables:
  IMAGE_URL: se_lab_1:$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA
  
build:
  stage: build
  image: docker:19.03.12
  tags:
    - docker
  script:
    - docker build . -t $IMAGE_URL
    - docker push $IMAGE_URL

deploy-production:
  stage: deploy-production
  image: kroniak/ssh-client:latest
  before_script:
    - echo $IMAGE_URL
  script:
    - docker run -d --name se_lab_1_container -p80:80 $IMAGE_URL
